name: Spec Update
on: 
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup Node.JS environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY_MM_DD
          utcOffset: "-08:00"
      - name: Install SDK
        run: |
          npm install
      - name: Update Modules
        run: |
          git submodule init
          git submodule update --remote --recursive
      - name: Generate Branch Name
        id: git-branch
        run: |
          echo "::set-output name=branch::spec_update_${{ steps.current-time.outputs.formattedTime }}"
      - name: Generate Num Diffs
        id: git-diff-num
        run: |
          cd generator/
          diffs=$(git diff --submodule dropbox-api-spec | grep "<" | wc -l)
          echo "::set-output name=num-diff::$diffs"
          cd ..
      - name: Generate Diff
        id: git-diff
        run: |
          cd generator/dropbox-api-spec
          gitdiff=$(git log -n ${{ steps.git-diff-num.outputs.num-diff }} --pretty="format:%H %n%n %b")
          diffmessage="\"Spec Update \n $gitdiff\""
          echo "::set-output name=diff::$diffmessage"
          cd ../..
      - name: Generate New Routes
        run: |
          git checkout -b ${{ steps.git-branch.outputs.branch }}
          cd generator/stone
          python setup.py install
          cd ..
          python generate_routes.py
          cd ..
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.3.0
        with:
          token: ${{ secrets.SPEC_UPDATE_TOKEN }}
          commit-message: ${{ steps.git-diff.outputs.diff }}
          branch: ${{ steps.git-branch.outputs.branch }}
          delete-branch: true
          base: 'master'
          title: 'Automated Spec Update'
          team-reviewers: |
            owners
            maintainers
          draft: false
