name: Spec Update
on: 
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2.1.2
        with:
          python-version: 3.7
      - name: Setup Node.JS environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY_MM_DD
          utcOffset: "-08:00"
      - name: Install SDK
        run: |
          npm install
      - name: Update Modules
        run: |
          git submodule init
          git submodule update --remote --recursive
      - name: Generate Branch Name
        id: git-branch
        run: |
          ::set-output branch=spec_update_${{ steps.current-time.outputs.formattedTime }}
      - name: Generate Num Diffs
        id: git-diff-num
        run: |
          cd generator/
          diffs=$(git diff --submodule dropbox-api-spec | grep "<" | wc -l)
          ::set-output num-diff=$diffs
          cd ..
      - name: Generate Diff
        id: git-diff
        run: |
          cd generator/dropbox-api-spec
          git-diff=$(git log -n ${{ steps.git-diff-num.outputs.num-diff }} --pretty="format:%H %n%n %b")
          ::set-output diff=$git-diff
          cd ../..
      - name: Generate New Routes & Create Diff
        run: |
          git checkout -b ${{ steps.git-branch.output.branch }}
          cd generator/stone
          python setup.py install
          cd ..
          python generate_routes.py
          cd ..
          git add .
          git commit -m ${{ steps.git-diff.outputs.diff }}
          git push --set-upstream origin ${{ steps.git-branch.output.branch }}
          git request-pull master https://github.com/rogebrd/dropbox-sdk-node.git ${{ steps.git-branch.output.branch }}